Added the ttbar analysis
atlas-outreach-data-tools/notebooks-collection-opendata pull request #48
Opened 2024-07-31 19:50 UTC by IoPapadopoulos

2024-08-15 14:04 UTC, Soap2G commented on 13-TeV-examples/uproot_python/ttbar_analysis.ipynb
> +    "def get_data_from_files(start, local):\n",
Here's a quick [set of suggestions on how to debug](https://chatgpt.com/share/822611d4-8332-4313-8e26-b9042e3d0583)

2024-08-17 14:56 UTC, IoPapadopoulos commented
I've updated the code to utilize pandas for managing data frames. During testing in Colab, the RAM usage peaked at 9GB. Additionally, I've added detailed content before each cell to enhance the code's user-friendliness. The only part I haven't modified is the def mtop() function, as each step is necessary to calculate the masses for both top quarks. However, I can consider splitting it into two separate functions for each top quark if needed.

2024-08-28 09:24 UTC, Soap2G requested changes
Hi @IoPapadopoulos, thanks a lot for the modifications, the notebook and the additional text is great!

I just left a few comments regarding some bits of code.
Thanks again, 
Best, 
Giovanni

2024-08-28 09:24 UTC, Soap2G commented on 13-TeV-examples/uproot_python/ttbar_analysis.ipynb
> +        "    print(f\"Error downloading data: {response.status_code}\")\n",
I'm wondering what is the rationale behind the downloading of files.
Typically we rely on the fact that we can "stream" the root files without downloading them in our local folder.
This comes with pros and cons:
- Pros:
  - We avoid to download huge files (i.e. huge time used to download them) that could or could not clog our computing sessions. What if we don't have enough space to download all the files? Then we don't run the notebook?
- Cons:
  - We might overload a bit eos, so we'll definitely need to address this issue

Is there any reason for which a user should prefer to download the files in their own temporary session or local pc, rather than exploit the fact that they are available online and without disk/space requirements?

If the download part is not needed, I suggest we remove it and stick to the streaming one, so that newcomers don't get confused.

## Additional context (if needed): 
We can have a look at how [other notebooks](https://github.com/atlas-outreach-data-tools/notebooks-collection-opendata/blob/master/13-TeV-examples/uproot_python/HyyAnalysis.ipynb) are done:
1. There is a general get_data funtion:
```python
def get_data_from_files():

    frames = [] # define empty list to hold data
    for val in samples_list: # loop over each file
        fileString = tuple_path+val+".GamGam.root" # file name to open
        temp = read_file(fileString,val) # call the function read_file defined below
        frames.append(temp) # append dataframe returned from read_file to list of dataframes
    data = pd.concat(frames) # concatenate list of dataframes together into one dataframe
    
    return data # return dataframe
```
2. There's a `read_file` function that just mounts the location of the sample, rather than downloading it:
```python
def read_file(path,sample):
    start = time.time() # start the clock
    print("Processing: "+sample) # print which sample is being processed
    data_all = pd.DataFrame() # define empty pandas DataFrame to hold all data for this sample
    tree = uproot.open(path + ":mini")
    numevents = tree.num_entries # number of events

etc...
```

2024-08-28 09:24 UTC, Soap2G commented on 13-TeV-examples/uproot_python/ttbar_analysis.ipynb
> +        "\n",
Again, I'm not against this strategy, but couldn't we setup a simple `for` loop that just encloses these steps into one?

2024-08-28 09:24 UTC, Soap2G commented on 13-TeV-examples/uproot_python/ttbar_analysis.ipynb
> +        "    'MC' : {  'list' : ['mc_410000.ttbar_lep'],},\n",
The `MC` nomenclature might me a bit misleading: is only this sample MonteCarlo? Then what are SingleTop and Diboson? I suggest we either rename MC somthing like "ttbar", or we add a MC prefix to all the MC samples.

2024-08-28 09:24 UTC, Soap2G commented on 13-TeV-examples/uproot_python/ttbar_analysis.ipynb
> +        "def download(url):\n",
An `import requests` might be missing here?
I see that the package is imported in a cell below, but hot here.

2024-08-28 09:24 UTC, Soap2G commented on 13-TeV-examples/uproot_python/ttbar_analysis.ipynb
> +        " $t\\bar{t}$ analysis code provided:\n",
We can add a link should the user be interested in more: https://atlas.cern/glossary

2024-09-11 20:17 UTC, IoPapadopoulos commented
Dear @Soap2G , thank for the comments. 

I update the code adding the glossary, change MC label to ttbar. Aslo I made the code to just streaming the database but i keeped the loop over the dataset. The reason is that, the dataset data_C and data_D are over 7 Gbs and 10 Gbs repeatedly. So I analyze a chunk of each dataset on its own, this way i keep the ram usage low. 

Thanks,
Best,
Giannhs

2024-10-09 08:35 UTC, merged

2024-10-09 08:49 UTC, AntonioJC commented
Hi @IoPapadopoulos, can you please add the plot of the final distribution to this notebook?

2024-10-09 09:39 UTC, IoPapadopoulos commented
Hi Antonio, just to make it clear from my side. You want me to add the two final plot in the end of the ttbar analysis. -------- Αρχικό μήνυμα --------Από: AntonioJC ***@***.***>Ημερομηνία: Τετ, 9 Οκτ 2024, 11:50 π.μ.Προς: atlas-outreach-data-tools/notebooks-collection-opendata ***@***.***>Κοιν.: Ioannhs_Papadopoulos ***@***.***>, Mention ***@***.***>Θέμα: Re: [atlas-outreach-data-tools/notebooks-collection-opendata] Added the ttbar analysis (PR #48)
Hi @IoPapadopoulos, can you please add the plot of the final distribution to this notebook?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-10-10 14:07 UTC, AntonioJC commented
Hi @IoPapadopoulos, yes, exactly, it's nice to show the final output of the code, gives an idea of what it does and it's more appealing