13 TeV cpp, pyroot, and Rdataframe notebooks
atlas-outreach-data-tools/notebooks-collection-opendata pull request #58
Opened 2024-09-10 12:06 UTC by marianaiv

I updated the notebooks for 13 TeV in the folders cpp, pyroot and Rdataframe.

I added documentation to the notebooks that made sense to me. [In this document](https://docs.google.com/document/d/1viCpYPxUGjC0xH9l87-vROixIxAckZI9BAwJ2XyADYU/edit?usp=sharing) I listed the notebooks that I think shouldn't be linked in the website and should probably be deleted (which are the ones I didn't added documentation to). I can delete them in this same PR if we agree about it.

Aside from the added documentation, I changed some file names and folder names so that the repository makes more sense. I'll update the links for everything in the website once we decide to merge.

2024-09-10 12:08 UTC, marianaiv commented
@Soap2G since I changed the name of some files/folders, how can I fix the automatic checks?

2024-09-10 14:38 UTC, Soap2G requested changes
Hi @marianaiv, thanks for the changes, looks very good to me! 

Let me just comment on a couple of points: 

1. Pipeline failing on 3 jobs: this is actually a bug, that is given by the fact that in the pipeline we make `git` detect all the modified files, and this includes the deleted ones. Therefore, the 3 jobs failing are failing because the script cannot `cd` into a folder that doesn't exist anymore. We can fix that in the workflow file to force [the command](https://github.com/atlas-outreach-data-tools/notebooks-collection-opendata/blob/cpp_pyroot/.github/workflows/single-notebook-check.yml#L27) to return only the added or modified files: 
```sh
DIFF=$(git diff --name-status origin/master...HEAD | grep -E '^[AM]' | grep ipynb || true)
```
where `grep -E '^[AM]' ` does that. Not 100% sure it works, needs to be tested.

2. the [general papermill](https://github.com/atlas-outreach-data-tools/notebooks-collection-opendata/blob/cpp_pyroot/.github/workflows/notebooks-runner-autocheck.yml) script (the one that runs on all the notebooks) is built to have hardcoded folders. In the case of python, the relevant line is [here](https://github.com/atlas-outreach-data-tools/notebooks-collection-opendata/blob/cpp_pyroot/.github/workflows/notebooks-runner-autocheck.yml#L54). We should change it to account for the `pyroot` folder, rather than `python`.

3. Just for the sake of completeness, I didn't see any conflicts wrt PR #57, so I believe we are good. But an additional eye doesn't hurt :)

2024-09-10 15:51 UTC, marianaiv commented
Hi @Soap2G,

Thanks for the insight!

On the notebooks: I didn't change the notebooks in the uproot folder. I'm waiting for that PR to be merge to start checking those 🙂

2025-05-02 11:45 UTC, zlmarshall approved these changes
This one looks great! The only question I have is whether we're going to induce a bunch of conflicts with !59 when this is merged, but I think we should go ahead.

2025-05-02 11:45 UTC, zlmarshall commented on 13-TeV-examples/cpp/ATLAS_OpenData_13-TeV_simple_cpp_example_histogram.ipynb
> +    "TFile *dataFile = TFile::Open(\"https://atlas-opendata.web.cern.ch/atlas-opendata/samples/2020/1largeRjet1lep/MC/mc_361106.Zee.1largeRjet1lep.root\");"
Just a comment in relation to the other notebooks in !59 — here we are using https :)

2025-05-02 11:48 UTC, zlmarshall commented
Ah, we have the left-over comment from @Soap2G about the papermill script here:

https://github.com/atlas-outreach-data-tools/notebooks-collection-opendata/blob/cpp_pyroot/.github/workflows/notebooks-runner-autocheck.yml#L68

which indeed should be changed as a part of this MR to get the CI going?

2025-05-02 13:10 UTC, marianaiv commented
@zlmarshall @Soap2G I think I did it?

2025-05-02 13:11 UTC, marianaiv commented
> This one looks great! The only question I have is whether we're going to induce a bunch of conflicts with !59 when this is merged, but I think we should go ahead.

This never touched uproot_python, which is the only change we touch lately

2025-05-02 13:20 UTC, zlmarshall approved these changes
Looks great to me!

2025-05-07 12:44 UTC, merged