Added plots in the ttbar
atlas-outreach-data-tools/notebooks-collection-opendata pull request #63
Opened 2024-10-10 16:58 UTC by IoPapadopoulos

2025-02-05 18:23 UTC, Soap2G requested changes
Hi @IoPapadopoulos, thanks for the update!

Here are a couple of suggestions coming from @alexander-held:

- the [vector](https://vector.readthedocs.io/) library would provide shortcuts for 4-vector math and simplify the code in some places, so might be worth a consideration
- the `uproot.open` call doesn't need the cycle (`key` in the notebook), it will just use the latest
- `cut_trig()` returns its argument so that function technically is not needed (but I understand if you want to keep the exact same interface for all cuts)
- `cut_charge()` can be simplified to `ak.sum(charge, axis=1) == 0`
- as far as I see, the dR cut for jets and muons will consider all jets, even those failing the jet selection cuts (same goes for the VBF cut), I'm not sure if this is on purpose

2025-02-06 18:50 UTC, IoPapadopoulos commented
Hi @Soap2G, thanks for the suggestions!

*I made the analysis run with parallel computing, reducing the runtime from 50 to 10 minutes.
*I tried to integrate the vector library into the code, but it keeps crashing. I’ll look into this again later.
*I fixed the issue with the key in uproot.open.
*I kept cut_trig() as is for consistency with the other cut functions.
*Thanks for the suggestion on cut_charge(), I updated it accordingly.
*Regarding the dR cut, yes, we need to check all the jets. For the VBF cut, I’ll double-check if it needs any adjustments.

Let me know if you have any other comments!

> Hi @IoPapadopoulos, thanks for the update!
> 
> Here are a couple of suggestions coming from @alexander-held:
> 
> * the [vector](https://vector.readthedocs.io/) library would provide shortcuts for 4-vector math and simplify the code in some places, so might be worth a consideration
> * the `uproot.open` call doesn't need the cycle (`key` in the notebook), it will just use the latest
> * `cut_trig()` returns its argument so that function technically is not needed (but I understand if you want to keep the exact same interface for all cuts)
> * `cut_charge()` can be simplified to `ak.sum(charge, axis=1) == 0`
> * as far as I see, the dR cut for jets and muons will consider all jets, even those failing the jet selection cuts (same goes for the VBF cut), I'm not sure if this is on purpose

2025-03-19 14:34 UTC, zlmarshall reviewed
Thanks very much for this MR! I've tried to add a few suggestions that I hope will help the clarity of the documentation. You did a very nice job, I think!

Cheers,
Zach

2025-03-19 14:34 UTC, zlmarshall commented on 13-TeV-examples/uproot_python/Hmumu.ipynb
> +        "By following this notebook, you will perform a $H \\rightarrow \\mu^+ \\mu^-$ search.You will apply a sequence of event selection criteria (cuts) to maximize the signal (events where $H \\ri
```suggestion
        "By following this notebook, you will perform a $H \\rightarrow \\mu^+ \\mu^-$ search. You will apply a sequence of event selection criteria (cuts) to maximize the signal (events where $H \\rightarrow \\mu^+ \\mu^-$) to background (other processes producing pairs of muons) ratio.\n",
```

2025-03-19 14:34 UTC, zlmarshall commented on 13-TeV-examples/uproot_python/Hmumu.ipynb
> +        "import warnings\n",
```suggestion
        "# Filter warnings that otherwise appear in output. These are normal in the running of this notebook.\n",
        "import warnings\n",
```

2025-03-19 14:34 UTC, zlmarshall commented on 13-TeV-examples/uproot_python/Hmumu.ipynb
> +        "lumi = 10000.\n",
Should this now be 36.? Also, above we talk about definitions in inverse femtobarns, but here I think we're in inverse picobarns? Maybe a comment on the units of this number?

2025-03-19 14:34 UTC, zlmarshall commented on 13-TeV-examples/uproot_python/Hmumu.ipynb
> +        "We select these samples below to capture both the signal and relevant background processes for the Higgs boson decay to muon pairs ($H \\rightarrow \\mu^+ \\mu^-$). The data samples include
```suggestion
        "We select these samples below to capture both the signal and relevant background processes for the Higgs boson decay to muon pairs ($H \\rightarrow \\mu^+ \\mu^-$). The data samples include all possible processes that produce a pair of muon-antinuon.  The background samples consist of simulated events chosen to account for the primary sources of noise in the analysis: the continuum Drell-Yan $\\mu^+ \\mu^-$production, which closely mimics the signal, and smaller contributions from $t\\bar{t}$ production and diboson or $W + jets$ processes. Including these samples allows us to model the background accurately and optimize cuts to enhance the signal-to-background ratio.",
        "Notice that we are using a 2 muon skim. Events have been pre-selected to include two good muons to reduce the total amount of data that must be processed."
```

2025-03-19 14:34 UTC, zlmarshall commented on 13-TeV-examples/uproot_python/Hmumu.ipynb
> +        "  Similarly, the function checks whether the number of particles passing the isolation criteria is greater than one for each event. This ensures that multiple particles in the event are well
```suggestion
        "  Similarly, the function checks whether the number of particles passing the isolation criteria is greater than one for each event. This ensures that multiple particles in the event are well-isolated. Non-isolated muons could be non-prompt ones coming from hadronic decays."
```

2025-03-19 14:34 UTC, zlmarshall commented on 13-TeV-examples/uproot_python/Hmumu.ipynb
> +        "      Ensures that at least two jets have b-tagging scores less than or equal to 3. Lower b-tagging scores indicate a higher probability of the jet contains b-quarks from decays of top quark
```suggestion
        "      Ensures that at least two jets have b-tagging scores less than or equal to 3. Lower b-tagging scores indicate a higher probability of the jet contains b-quarks from decays of top quarks, which could contain non-prompt background muons (e.g. muons from hadron decays, rather than from Higgs bosons).\n",
```

2025-03-19 14:34 UTC, zlmarshall commented on 13-TeV-examples/uproot_python/Hmumu.ipynb
> +        "    DR_M1 = np.sqrt((eta - eta_M[:,0])**2 + (phi -  phi_M[:,0])**2)\n",
This is fine for delta eta, but phi is periodic. What happens when a jet has phi=3.1 and a muon has phi=-3.1, and what should happen?

2025-03-19 14:34 UTC, zlmarshall commented on 13-TeV-examples/uproot_python/Hmumu.ipynb
> +        "* Alternate Selection Option: Consider relaxing the VBF cuts (e.g. lowering the invariant mass) or switching to a ggF-based selection."
```suggestion
        "* Alternate Selection Option: Consider relaxing the VBF cuts (e.g. lowering the invariant mass) or switching to a ggF-based selection. ggF normally does not have significant jet activity, so one can try a jet veto instead."
```

2025-03-19 14:34 UTC, zlmarshall commented on 13-TeV-examples/uproot_python/Hmumu.ipynb
> +        "  * This selection cut ensures that the event contains at least two jets that satisfy specific criteria for energy, transverse momentum, and b-tagging. The two jets come from the production
```suggestion
        "  * This selection cut ensures that the event contains at least two jets that satisfy specific criteria for energy, transverse momentum, and b-tagging. The two jets come from the production of the Higgs boson, normally in the Vector Boson Fusion mechanism, which is one of the dominant production mechanisms. The gluon-gluon fusion (ggF) production mechanism is more common, but can be harder to distinguish from the background because of its relatively lower jet activity.\n",
```

2025-03-19 14:34 UTC, zlmarshall commented on 13-TeV-examples/uproot_python/Hmumu.ipynb
> +        "        tuple_path = \"https://cernbox.cern.ch/files/spaces/eos/user/e/egramsta/OpenData/NOV2024/2muons/\"\n",
This is what we should update to use the 'final' location of the files.

2025-03-27 17:30 UTC, IoPapadopoulos commented
I made all the changes from Zack's comments except for the one regarding the DR. I will speak with Ms. Christina to resolve it

2025-04-24 12:34 UTC, zlmarshall reviewed
Thanks for the updates! Just a few questions about the new files...

Best,
Zach

2025-04-24 12:34 UTC, zlmarshall commented on 13-TeV-examples/uproot_python/Hmumu.ipynb
> +        "    #main_axes.text(0.05, 0.82, r'$\\sqrt{s}$=13 TeV, 10 fb$^{-1}$', transform=main_axes.transAxes)\n",
Still 10/fb?

2025-04-24 12:34 UTC, zlmarshall commented on 13-TeV-examples/uproot_python/Hmumu.ipynb
> +        "        #################### change to the final location of the files #######################\n",
Reminder that we can use `root://eospublic.cern.ch//eos/opendata/atlas/rucio/user/egramsta/` as the path to the files now

2025-04-24 12:34 UTC, zlmarshall commented on 13-TeV-examples/uproot_python/Hmumu.ipynb
> +        "    Dphi1 = phi -  phi_M[:,0]\n",
I think this still has the same phi-periodicity problem? e.g. if `phi=-3.1` and `phi_M=3.1`, then `Dphi1=-6.2`, even though they are only 0.08 units apart? One common trick is to use `asin` and `sin`, like: `dPhi = asin( sin( phi-phiM ) )`, which has the right domain.

2025-04-24 12:34 UTC, zlmarshall commented on 13-TeV-examples/uproot_python/ttbar_analysis.ipynb
> +        "!pip install uproot"
Standard question for @Soap2G as to whether this is needed

2025-04-24 13:20 UTC, IoPapadopoulos commented on 13-TeV-examples/uproot_python/Hmumu.ipynb
> +        "    #main_axes.text(0.05, 0.82, r'$\\sqrt{s}$=13 TeV, 10 fb$^{-1}$', transform=main_axes.transAxes)\n",
No, it should be. thirty 36 fb.

2025-04-24 13:23 UTC, IoPapadopoulos commented on 13-TeV-examples/uproot_python/ttbar_analysis.ipynb
> +        "!pip install uproot"
The google colab  does not come with the uproot to installed. So I have to install it every time. This is why it's the first thing on the notebook.

2025-04-25 07:07 UTC, IoPapadopoulos commented on 13-TeV-examples/uproot_python/Hmumu.ipynb
> +        "        #################### change to the final location of the files #######################\n",
I did update the path to the files.

2025-04-25 07:08 UTC, IoPapadopoulos commented on 13-TeV-examples/uproot_python/ttbar_analysis.ipynb
> +        "        tuple_path = \"https://cernbox.cern.ch/files/spaces/eos/user/e/egramsta/OpenData/FEB2025/1LMET30/\"\n",
I did update the path to the files.

2025-04-25 07:10 UTC, IoPapadopoulos commented on 13-TeV-examples/uproot_python/Hmumu.ipynb
> +        "    Dphi1 = phi -  phi_M[:,0]\n",
I went ahead and updated the equation to use the expression you suggested

2025-04-25 14:07 UTC, zlmarshall commented on 13-TeV-examples/uproot_python/ttbar_analysis.ipynb
> +        "!pip install fsspec-xrootd\n",
@marianaiv and @Soap2G we should agree on how to handle this I think

2025-04-25 14:10 UTC, zlmarshall commented
Thanks @IoPapadopoulos ! It looks good to me at this point. We just have to make sure we're consistent on how to handle the file reading from the open data portal (was just talking to Mariana and Giovanni about that today, so I think we have a solution, or 90% of one)

2025-04-26 14:03 UTC, Soap2G commented on 13-TeV-examples/uproot_python/ttbar_analysis.ipynb
> +        "!pip install fsspec-xrootd\n",
Also, https://github.com/atlas-outreach-data-tools/atlasopenmagic/pull/10

2025-04-26 20:22 UTC, zlmarshall commented on 13-TeV-examples/uproot_python/ttbar_analysis.ipynb
> +        "!pip install fsspec-xrootd\n",
Just so I'm sure, that PR (with atlasopenmagic 0.4.0 when it's released) would change the code into something more like:

```
import subprocess,sys
subprocess.run([sys.executable, "-m", "pip", "install", "--upgrade", "--user","atlasopenmagic"])
from atlasopenmagic import install_from_environment
required_packages = ['coffea', 'hist', 'dask', 'numpy', 'matplotlib']
install_from_environment(required_packages, environment_file="../../binder/environment.yml")
```

?

2025-04-27 13:29 UTC, Soap2G commented on 13-TeV-examples/uproot_python/ttbar_analysis.ipynb
> +        "!pip install fsspec-xrootd\n",
Yeah, it could also be 
```python
!pip install atlasopenmagic
from atlasopenmagic import install_from_environment
install_from_environment('coffea', 'hist', 'dask', 'numpy', 'matplotlib', environment_file="../../binder/environment.yml")
```

There is still some convolution, but at least one doesn't have to worry about versions, and everything depends from environment.yml

2025-05-01 21:19 UTC, zlmarshall commented on 13-TeV-examples/uproot_python/ttbar_analysis.ipynb
> +        "!pip install fsspec-xrootd\n",
Just a note to say that this should now be working with the other merges done today. That should make your life a bit simpler :)

2025-05-02 09:39 UTC, marianaiv requested changes
Hi @IoPapadopoulos!

Thank you for the work. I really appreciate the documentation on these. Added some comments, mostly about using atlasopenmagic, and one for the looping and saving cuts.

2025-05-02 09:39 UTC, marianaiv commented on 13-TeV-examples/uproot_python/Hmumu.ipynb
> +        "import warnings\n",
Now we have a function in atlasopenmagic to setup the notebooks
```
import atlasopenmagic as atom
atom.install_from_environment()
```
This should be enough, it would install all in the environment file from this repository. If you want to add a package that is not in the environment, you can do it listing them:
```
atom.install_from_environment('package1', 'package2')
```
Nothing should be missing from the environment though, so let us know is that is the case

2025-05-02 09:39 UTC, marianaiv commented on 13-TeV-examples/uproot_python/Hmumu.ipynb
> +        "                        }"
For the samples we also now have a helper function. You can use it like:
```
mc_defs = {
    r'Background $t\bar t$':    {'dids': [410470],                      'color': 'yellow'},
    r'Background $V+$jets':     {'dids': [700335,700336,700337],        'color': 'orange'},
    r'Background Diboson':      {'dids': [700488,700489,700490,700491],'color': 'green'},
    r'Background $ZZ^{*}$':     {'dids': [700600,700601],               'color': '#ff0000'},
    r'Signal ($m_H$=125 GeV)':  {'dids': [345060,346228],              'color': '#00cdff'},
}

mc_samples   = build_mc_dataset(mc_defs,   skim='2bjets', protocol='https')
data_samples = build_data_dataset('2bjets',  color='red', protocol='https')

samples = {**data_samples, **mc_samples}
```
the color is optional.

This should give you the dict with all the urls you will need to stream the data.

2025-05-02 09:39 UTC, marianaiv commented on 13-TeV-examples/uproot_python/Hmumu.ipynb
> +        "    *   Purpose: The cut checks if the number of leptons in the event (lep_n) is exactly equal to 2. Events with two leptons are selected for further analysis, as this is a signature of the
For some reason this is not rendering correctly. Maybe is indented more than once? that's markdown signal for code

2025-05-02 09:39 UTC, marianaiv commented on 13-TeV-examples/uproot_python/Hmumu.ipynb
> +        "    print(f\"{round(i*fraction*100)}% of the analysis completed in {round(elapsed_time / 60, 1)} min \\n\")"
Creating empty dataframes and filling in a loop is very memory inefficient. I suggest to fill dictionaries and concatenate at the end. Something like:
```
samples = ["data", "mumu", "Higgs", "ttbar"]
results = {s: [] for s in samples}

# Loop over chunks and append to lists
for i in range(number_of_loops):
    for sample in samples:
        chunk_df = parallel_analysis(sample, i)
        results[sample].append(chunk_df)
    elapsed = time.time() - start_time
    percent = (i + 1) / number_of_loops * 100
    print(f"{percent:.0f}% done in {elapsed/60:.1f} min")

# Single concat 
Data_df  = pd.concat(results["data"],  ignore_index=True)
mumu_df  = pd.concat(results["mumu"],  ignore_index=True)
Higgs_df = pd.concat(results["Higgs"], ignore_index=True)
ttbar_df = pd.concat(results["ttbar"], ignore_index=True)
```

2025-05-02 09:39 UTC, marianaiv commented on 13-TeV-examples/uproot_python/Hmumu.ipynb
> +      "execution_count": null,
Would be good to have the notebook with the outputs to check what we are getting here. You just need to save it after running it and commit/push so that it is uploaded with all the outputs.

2025-05-02 09:39 UTC, marianaiv commented on 13-TeV-examples/uproot_python/ttbar_analysis.ipynb
> +        "!pip install fsspec-xrootd\n",
This should now be:
```
from atlasopenmagic import install_from_environment
install_from_enviroment()
```

2025-05-02 09:39 UTC, marianaiv commented on 13-TeV-examples/uproot_python/ttbar_analysis.ipynb
> +        "samples = {\n",
Same comment here as for the Hmumu notebook.
```
import atlasopenmagic as atom
mc_defs = {
    r'Background $t\bar t$':    {'dids': [410470],                      'color': 'yellow'},
    r'Background $V+$jets':     {'dids': [700335,700336,700337],        'color': 'orange'},
    r'Background Diboson':      {'dids': [700488,700489,700490,700491],'color': 'green'},
    r'Background $ZZ^{*}$':     {'dids': [700600,700601],               'color': '#ff0000'},
    r'Signal ($m_H$=125 GeV)':  {'dids': [345060,346228],              'color': '#00cdff'},
}

mc_samples   = atom.build_mc_dataset(mc_defs,   skim='2bjets', protocol='https')
data_samples = atom.build_data_dataset('2bjets',  color='red', protocol='https')

samples = {**data_samples, **mc_samples}
```
Something like this.

2025-05-02 09:39 UTC, marianaiv commented on 13-TeV-examples/uproot_python/ttbar_analysis.ipynb
> +        "   *     Purpose: The cut ensures that one lepton in the event is associated with a trigger, meaning it was responsible for the event being recorded. Applying this cut reduces backgrounds fr
This bullet point also has a weird font. Maybe it has extra spaces and it is taken as code?

2025-05-02 09:39 UTC, marianaiv commented on 13-TeV-examples/uproot_python/ttbar_analysis.ipynb
> +        "Data_df = pd.DataFrame()\n",
Same comment here as in the other notebook. Creating empty dataframes and filling in a loop is slow.

2025-05-02 09:39 UTC, marianaiv commented on 13-TeV-examples/uproot_python/ttbar_analysis.ipynb
> +      "execution_count": null,
And same comment, please upload it with the outputs :)

2025-05-02 12:02 UTC, IoPapadopoulos commented on 13-TeV-examples/uproot_python/Hmumu.ipynb
> +        "    *   Purpose: The cut checks if the number of leptons in the event (lep_n) is exactly equal to 2. Events with two leptons are selected for further analysis, as this is a signature of the
Fixed it.

2025-05-27 10:43 UTC, IoPapadopoulos commented
I updated both analyses, they now use ATLAS Open Magic. However, I encountered a problem with the output on both analyses.

2025-05-27 13:11 UTC, zlmarshall commented
Hi @IoPapadopoulos ,

What's the problem with the output in the analyses?

Best,
Zach

2025-06-12 08:56 UTC, IoPapadopoulos commented
Hi @marianaiv,

I have addeed the following lines in the start of both analyses.

```
#install required packages
import sys
!pip install atlasopenmagic
from atlasopenmagic import install_from_environment
install_from_environment()
```
If you have any further comments or suggestions, please feel free to let me know.

Best, 
Giannis

2025-06-12 10:22 UTC, marianaiv approved these changes
Thanks @IoPapadopoulos, this is great!
For me this is good to go.

2025-06-12 10:54 UTC, zlmarshall commented on 13-TeV-examples/uproot_python/ttbar_analysis.ipynb
> +        "   *     Purpose: The cut ensures that one lepton in the event is associated with a trigger, meaning it was responsible for the event being recorded. Applying this cut reduces backgrounds fr
Let's live with it for now :)

2025-06-12 10:55 UTC, zlmarshall approved these changes

2025-06-12 10:58 UTC, merged